In [632]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt     
import seaborn as sns

In [633]:
df=pd.read_csv("heart.csv")

In [634]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [635]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [636]:
df.size

4242

In [637]:
df.shape

(303, 14)

In [638]:
x=df.drop("target",axis=1)

In [639]:
x

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2

In [640]:
y=df["target"]

In [641]:
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [642]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [643]:
num_column=x.select_dtypes(exclude="O").columns

In [644]:
num_column

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal'],
      dtype='object')

In [645]:
cat_column=x.select_dtypes(include="O").columns

In [646]:
cat_column

Index([], dtype='object')

In [647]:
from sklearn.impute import SimpleImputer ## HAndling Missing Values
from sklearn.preprocessing import StandardScaler # HAndling Feature Scaling
from sklearn.preprocessing import OrdinalEncoder # Ordinal Encoding
## pipelines
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [648]:
num_pipeline=Pipeline(
  
  steps= [
    ('imputer',SimpleImputer()),
    ('scaler',StandardScaler())
    
    
  ]
    
)

In [649]:
preprocessor = ColumnTransformer(
    [
    ('num_pipeline',num_pipeline,num_column)
    ])

In [650]:
from sklearn.model_selection import train_test_split

In [651]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [652]:
x_train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
132,42,1,1,120,295,0,1,162,0,0.0,2,0,2
202,58,1,0,150,270,0,0,111,1,0.8,2,0,3
196,46,1,2,150,231,0,1,147,0,3.6,1,0,2
75,55,0,1,135,250,0,0,161,0,1.4,1,0,2
176,60,1,0,117,230,1,1,160,1,1.4,2,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
188,50,1,2,140,233,0,1,163,0,0.6,1,1,3
71,51,1,2,94,227,0,1,154,1,0.0,2,1,3
106,69,1,3,160,234,1,0,131,0,0.1,1,1,2
270,46,1,0,120,249,0,0,144,0,0.8,2,0,3
102,63,0,1,140,195,0,1,179,0,0.0,2,2,2

In [653]:
x_test

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
179,57,1,0,150,276,0,0,112,1,0.6,1,1,1
228,59,1,3,170,288,0,0,159,0,0.2,1,0,3
111,57,1,2,150,126,1,1,173,0,0.2,2,1,3
246,56,0,0,134,409,0,0,150,1,1.9,1,2,3
60,71,0,2,110,265,1,0,130,0,0.0,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,69,1,2,140,254,0,0,146,0,2.0,1,3,3
104,50,1,2,129,196,0,1,163,0,0.0,2,0,2
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3
193,60,1,0,145,282,0,0,142,1,2.8,1,2,3
184,50,1,0,150,243,0,0,128,0,2.6,1,0,3

In [654]:
x_train.shape

(242, 13)

In [655]:
x_test.shape

(61, 13)

In [656]:

preprocessor.fit_transform(x_train)

array([[-1.35679832,  0.72250438,  0.00809909, ...,  0.95390513,
        -0.68970073, -0.50904773],
       [ 0.38508599,  0.72250438, -0.97189094, ...,  0.95390513,
        -0.68970073,  1.17848036],
       [-0.92132724,  0.72250438,  0.98808912, ..., -0.69498803,
        -0.68970073, -0.50904773],
       ...,
       [ 1.58263146,  0.72250438,  1.96807914, ..., -0.69498803,
         0.32186034, -0.50904773],
       [-0.92132724,  0.72250438, -0.97189094, ...,  0.95390513,
        -0.68970073,  1.17848036],
       [ 0.92942484, -1.38407465,  0.00809909, ...,  0.95390513,
         1.33342142, -0.50904773]])

In [657]:

preprocessor.transform(x_test)

array([[ 2.76218225e-01,  7.22504380e-01, -9.71890936e-01,
         1.16949120e+00,  5.53408401e-01, -3.83300706e-01,
        -1.04610909e+00, -1.70875171e+00,  1.47790748e+00,
        -3.75556294e-01, -6.94988026e-01,  3.21860343e-01,
        -2.19657581e+00],
       [ 4.93953764e-01,  7.22504380e-01,  1.96807914e+00,
         2.36038903e+00,  7.81171723e-01, -3.83300706e-01,
        -1.04610909e+00,  3.98288831e-01, -6.76632341e-01,
        -7.39094787e-01, -6.94988026e-01, -6.89700735e-01,
         1.17848036e+00],
       [ 2.76218225e-01,  7.22504380e-01,  9.88089118e-01,
         1.16949120e+00, -2.29363312e+00,  2.60891771e+00,
         8.43132697e-01,  1.02591793e+00, -6.76632341e-01,
        -7.39094787e-01,  9.53905134e-01,  3.21860343e-01,
         1.17848036e+00],
       [ 1.67350456e-01, -1.38407465e+00, -9.71890936e-01,
         2.16772932e-01,  3.07778522e+00, -3.83300706e-01,
        -1.04610909e+00, -5.18701733e-03,  1.47790748e+00,
         8.05943807e-01, -6.94988026e-01,  1.33342142e+00,
         1.17848036e+00],
       [ 1.80036700e+00, -1.38407465e+00,  9.88089118e-01,
        -1.21230447e+00,  3.44625356e-01,  2.60891771e+00,
        -1.04610909e+00, -9.01800013e-01, -6.76632341e-01,
        -9.20864033e-01,  9.53905134e-01,  3.21860343e-01,
        -5.09047728e-01],
       [ 2.76218225e-01,  7.22504380e-01,  9.88089118e-01,
         1.16949120e+00, -1.49646149e+00, -3.83300706e-01,
         8.43132697e-01,  1.07074858e+00, -6.76632341e-01,
         5.33289937e-01,  9.53905134e-01, -6.89700735e-01,
        -5.09047728e-01],
       [-9.21327240e-01, -1.38407465e+00, -9.71890936e-01,
         4.54952499e-01, -7.29407332e-02, -3.83300706e-01,
        -1.04610909e+00,  8.44742822e-02,  1.47790748e+00,
        -9.20864033e-01, -6.94988026e-01, -6.89700735e-01,
        -5.09047728e-01],
       [ 1.67350456e-01, -1.38407465e+00, -9.71890936e-01,
         4.14673578e+00,  7.81171723e-01,  2.60891771e+00,
        -1.04610909e+00, -7.67308064e-01,  1.47790748e+00,
         2.71452089e+00, -2.34388119e+00,  1.33342142e+00,
         1.17848036e+00],
       [-5.03850834e-02,  7.22504380e-01, -9.71890936e-01,
        -4.97765768e-01,  7.43211169e-01, -3.83300706e-01,
        -1.04610909e+00, -1.52942911e+00,  1.47790748e+00,
         1.98744391e+00, -6.94988026e-01,  1.33342142e+00,
        -5.09047728e-01],
       [-5.03850834e-02,  7.22504380e-01,  9.88089118e-01,
        -3.19131093e-01,  4.96467571e-01, -3.83300706e-01,
        -1.04610909e+00,  8.44742822e-02, -6.76632341e-01,
        -4.66440917e-01, -2.34388119e+00,  3.21860343e-01,
        -5.09047728e-01],
       [ 2.76218225e-01,  7.22504380e-01, -9.71890936e-01,
         5.74042282e-01, -1.04093485e+00, -3.83300706e-01,
         8.43132697e-01, -9.48483169e-02, -6.76632341e-01,
        -5.57325540e-01, -6.94988026e-01, -6.89700735e-01,
        -2.19657581e+00],
       [ 4.93953764e-01,  7.22504380e-01,  1.96807914e+00,
         2.83674817e+00,  4.39526740e-01, -3.83300706e-01,
        -1.04610909e+00, -2.29340266e-01, -6.76632341e-01,
         2.89629014e+00, -2.34388119e+00, -6.89700735e-01,
         1.17848036e+00],
       [-2.68120623e-01,  7.22504380e-01,  8.09909113e-03,
        -6.16855552e-01,  1.48344196e+00, -3.83300706e-01,
         8.43132697e-01,  9.81087278e-01, -6.76632341e-01,
        -7.39094787e-01,  9.53905134e-01, -6.89700735e-01,
        -5.09047728e-01],
       [-1.57453386e+00,  7.22504380e-01, -9.71890936e-01,
        -1.21230447e+00, -1.51544177e+00, -3.83300706e-01,
        -1.04610909e+00, -1.61909041e+00,  1.47790748e+00,
         8.96828430e-01, -6.94988026e-01, -6.89700735e-01,
         1.17848036e+00],
       [-9.21327240e-01, -1.38407465e+00,  8.09909113e-03,
        -1.51002893e+00, -8.13171528e-01, -3.83300706e-01,
         8.43132697e-01,  9.81087278e-01, -6.76632341e-01,
        -9.20864033e-01,  9.53905134e-01, -6.89700735e-01,
        -5.09047728e-01],
       [-1.13906278e+00,  7.22504380e-01,  9.88089118e-01,
         5.74042282e-01, -2.24782948e-01, -3.83300706e-01,
        -1.04610909e+00,  1.33973248e+00, -6.76632341e-01,
        -9.20864033e-01,  9.53905134e-01, -6.89700735e-01,
        -5.09047728e-01],
       [-2.22774047e+00, -1.38407465e+00,  8.09909113e-03,
        -7.35945335e-01, -6.99289868e-01, -3.83300706e-01,
         8.43132697e-01,  1.87770027e+00, -6.76632341e-01,
        -2.84671671e-01,  9.53905134e-01, -6.89700735e-01,
        -5.09047728e-01],
       [-5.03850834e-02,  7.22504380e-01, -9.71890936e-01,
        -6.16855552e-01, -1.11685596e+00, -3.83300706e-01,
         8.43132697e-01, -1.66392106e+00, -6.76632341e-01,
         3.51520691e-01, -6.94988026e-01,  3.21860343e-01,
         1.17848036e+00],
       [-9.21327240e-01,  7.22504380e-01, -9.71890936e-01,
         5.74042282e-01,  1.21771809e+00, -3.83300706e-01,
         8.43132697e-01, -1.35010651e+00,  1.47790748e+00,
         7.15059184e-01, -6.94988026e-01,  1.33342142e+00,
         1.17848036e+00],
       [ 7.11689304e-01,  7.22504380e-01, -9.71890936e-01,
         4.54952499e-01, -1.53442205e+00, -3.83300706e-01,
        -1.04610909e+00, -1.12595326e+00,  1.47790748e+00,
         2.35098240e+00, -6.94988026e-01,  3.21860343e-01,
        -5.09047728e-01],
       [ 1.03829261e+00,  7.22504380e-01,  1.96807914e+00,
         2.36038903e+00, -3.76625162e-01, -3.83300706e-01,
        -1.04610909e+00,  2.18966232e-01, -6.76632341e-01,
        -3.75556294e-01, -6.94988026e-01, -6.89700735e-01,
         1.17848036e+00],
       [ 1.67350456e-01,  7.22504380e-01, -9.71890936e-01,
        -2.14066346e-02,  6.86270339e-01,  2.60891771e+00,
        -1.04610909e+00, -2.11222756e+00,  1.47790748e+00,
         5.33289937e-01, -2.34388119e+00, -6.89700735e-01,
         1.17848036e+00],
       [ 1.36489592e+00,  7.22504380e-01, -9.71890936e-01,
        -6.16855552e-01, -1.86822394e-01, -3.83300706e-01,
         8.43132697e-01, -3.54680835e+00, -6.76632341e-01,
        -1.20178014e-02, -6.94988026e-01, -6.89700735e-01,
        -5.09047728e-01],
       [ 1.80036700e+00, -1.38407465e+00,  8.09909113e-03,
         1.76494012e+00,  1.04689560e+00, -3.83300706e-01,
         8.43132697e-01,  5.32780780e-01, -6.76632341e-01,
        -5.57325540e-01,  9.53905134e-01,  1.33342142e+00,
        -5.09047728e-01],
       [-1.13906278e+00, -1.38407465e+00,  9.88089118e-01,
        -7.35945335e-01, -9.19210100e-02, -3.83300706e-01,
         8.43132697e-01, -5.00176671e-02, -6.76632341e-01,
        -6.48210163e-01, -6.94988026e-01,  3.21860343e-01,
        -5.09047728e-01],
       [-1.57453386e+00,  7.22504380e-01, -9.71890936e-01,
         1.28858098e+00, -4.52546269e-01, -3.83300706e-01,
         8.43132697e-01,  1.38456313e+00, -6.76632341e-01,
        -9.20864033e-01,  9.53905134e-01, -6.89700735e-01,
         1.17848036e+00],
       [ 4.93953764e-01,  7.22504380e-01,  1.96807914e+00,
         1.76494012e+00,  4.96467571e-01, -3.83300706e-01,
        -1.04610909e+00, -1.12595326e+00, -6.76632341e-01,
        -9.20864033e-01,  9.53905134e-01, -6.89700735e-01,
        -5.09047728e-01],
       [-3.76988392e-01,  7.22504380e-01, -9.71890936e-01,
         5.74042282e-01,  2.68704249e-01, -3.83300706e-01,
        -1.04610909e+00,  1.60871637e+00,  1.47790748e+00,
        -9.20864033e-01,  9.53905134e-01, -6.89700735e-01,
        -5.09047728e-01],
       [ 2.76218225e-01,  7.22504380e-01, -9.71890936e-01,
         2.06266458e+00,  8.00152000e-01,  2.60891771e+00,
        -1.04610909e+00, -1.17078391e+00, -6.76632341e-01,
        -1.20178014e-02, -6.94988026e-01,  2.34498250e+00,
         1.17848036e+00],
       [-4.85856162e-01, -1.38407465e+00, -9.71890936e-01,
        -1.21230447e+00,  1.35842312e-01, -3.83300706e-01,
        -1.04610909e+00,  3.98288831e-01, -6.76632341e-01,
        -9.20864033e-01,  9.53905134e-01, -6.89700735e-01,
        -5.09047728e-01],
       [ 1.03829261e+00,  7.22504380e-01, -9.71890936e-01,
        -1.40496418e-01,  3.06664803e-01, -3.83300706e-01,
         8.43132697e-01, -2.02256626e+00,  1.47790748e+00,
        -7.39094787e-01, -6.94988026e-01,  3.21860343e-01,
         1.17848036e+00],
       [ 7.11689304e-01,  7.22504380e-01, -9.71890936e-01,
         5.74042282e-01, -7.56230698e-01, -3.83300706e-01,
        -1.04610909e+00, -5.43154815e-01,  1.47790748e+00,
         8.05943807e-01,  9.53905134e-01,  3.21860343e-01,
         1.17848036e+00],
       [ 8.20557073e-01,  7.22504380e-01, -9.71890936e-01,
        -6.16855552e-01,  3.82585910e-01, -3.83300706e-01,
         8.43132697e-01, -2.29155016e+00,  1.47790748e+00,
         7.15059184e-01, -6.94988026e-01,  1.33342142e+00,
         1.17848036e+00],
       [-1.03019501e+00,  7.22504380e-01, -9.71890936e-01,
        -1.56957382e+00, -7.37250421e-01, -3.83300706e-01,
        -1.04610909e+00, -9.48483169e-02,  1.47790748e+00,
         1.80567466e+00, -6.94988026e-01, -6.89700735e-01,
        -5.09047728e-01],
       [ 1.25602815e+00, -1.38407465e+00,  1.96807914e+00,
         1.16949120e+00, -3.95605439e-01, -3.83300706e-01,
         8.43132697e-01, -1.61909041e+00, -6.76632341e-01,
         1.44213617e+00, -2.34388119e+00, -6.89700735e-01,
        -5.09047728e-01],
       [ 9.29424843e-01,  7.22504380e-01, -9.71890936e-01,
        -2.14066346e-02,  1.35842312e-01, -3.83300706e-01,
        -1.04610909e+00, -1.39678967e-01, -6.76632341e-01,
         3.51520691e-01, -6.94988026e-01,  3.21860343e-01,
         1.17848036e+00],
       [-3.76988392e-01,  7.22504380e-01,  9.88089118e-01,
        -3.19131093e-01, -3.49801796e-02,  2.60891771e+00,
        -1.04610909e+00,  7.12103379e-01, -6.76632341e-01,
         1.26036692e+00, -6.94988026e-01, -6.89700735e-01,
        -5.09047728e-01],
       [-7.03591701e-01,  7.22504380e-01,  9.88089118e-01,
        -3.78675985e-01,  1.54822588e-01,  2.60891771e+00,
         8.43132697e-01,  1.11557923e+00, -6.76632341e-01,
        -9.20864033e-01,  9.53905134e-01,  1.33342142e+00,
        -5.09047728e-01],
       [-1.57453386e+00,  7.22504380e-01,  1.96807914e+00,
         5.74042282e-01, -9.08072912e-01, -3.83300706e-01,
         8.43132697e-01,  1.25007118e+00,  1.47790748e+00,
         3.51520691e-01,  9.53905134e-01, -6.89700735e-01,
         1.17848036e+00],
       [-1.03019501e+00,  7.22504380e-01, -9.71890936e-01,
        -9.14580010e-01,  2.49723972e-01, -3.83300706e-01,
        -1.04610909e+00,  1.56388572e+00, -6.76632341e-01,
        -9.20864033e-01,  9.53905134e-01, -6.89700735e-01,
        -5.09047728e-01],
       [-2.68120623e-01,  7.22504380e-01,  9.88089118e-01,
         4.54952499e-01, -4.52546269e-01, -3.83300706e-01,
         8.43132697e-01,  8.46595328e-01, -6.76632341e-01,
        -9.20864033e-01,  9.53905134e-01,  3.35654358e+00,
        -5.09047728e-01],
       [ 4.93953764e-01,  7.22504380e-01,  8.09909113e-03,
         5.74042282e-01, -4.90506823e-01, -3.83300706e-01,
         8.43132697e-01,  6.22442080e-01,  1.47790748e+00,
        -9.20864033e-01,  9.53905134e-01, -6.89700735e-01,
        -5.09047728e-01],
       [ 8.20557073e-01,  7.22504380e-01,  8.09909113e-03,
        -1.40496418e-01, -7.37250421e-01,  2.60891771e+00,
        -1.04610909e+00, -4.53493515e-01, -6.76632341e-01,
        -9.20864033e-01,  9.53905134e-01, -6.89700735e-01,
        -5.09047728e-01],
       [-1.46566609e+00,  7.22504380e-01,  9.88089118e-01,
        -2.14066346e-02, -6.23368760e-01, -3.83300706e-01,
        -1.04610909e+00,  8.01764679e-01, -6.76632341e-01,
         8.96828430e-01, -6.94988026e-01, -6.89700735e-01,
        -5.09047728e-01],
       [-1.13906278e+00,  7.22504380e-01,  8.09909113e-03,
        -6.16855552e-01,  3.06664803e-01, -3.83300706e-01,
         8.43132697e-01,  1.02591793e+00, -6.76632341e-01,
        -9.20864033e-01,  9.53905134e-01, -6.89700735e-01,
         1.17848036e+00],
       [-1.24793055e+00,  7.22504380e-01, -9.71890936e-01,
         9.76831488e-02,  2.98037404e-03,  2.60891771e+00,
        -1.04610909e+00, -3.19001566e-01,  1.47790748e+00,
        -8.29979410e-01, -6.94988026e-01,  3.35654358e+00,
         1.17848036e+00],
       [-2.68120623e-01,  7.22504380e-01, -9.71890936e-01,
        -1.40496418e-01, -8.13171528e-01,  2.60891771e+00,
         8.43132697e-01,  2.63796881e-01,  1.47790748e+00,
        -1.20178014e-02, -6.94988026e-01, -6.89700735e-01,
        -3.88410390e+00],
       [-2.68120623e-01,  7.22504380e-01,  8.09909113e-03,
        -1.40496418e-01, -7.94191252e-01,  2.60891771e+00,
         8.43132697e-01,  1.51905508e+00, -6.76632341e-01,
        -9.20864033e-01,  9.53905134e-01, -6.89700735e-01,
        -5.09047728e-01],
       [ 3.85085995e-01, -1.38407465e+00, -9.71890936e-01,
         2.36038903e+00, -4.14585716e-01,  2.60891771e+00,
        -1.04610909e+00, -1.84509616e-01,  1.47790748e+00,
         1.62390542e+00, -6.94988026e-01,  1.33342142e+00,
        -2.19657581e+00],
       [ 5.84826861e-02,  7.22504380e-01, -9.71890936e-01,
         1.76494012e+00,  8.00152000e-01, -3.83300706e-01,
        -1.04610909e+00, -2.29340266e-01,  1.47790748e+00,
        -1.93787048e-01, -6.94988026e-01,  3.21860343e-01,
         1.17848036e+00],
       [-7.03591701e-01,  7.22504380e-01, -9.71890936e-01,
        -2.14066346e-02,  1.73802865e-01,  2.60891771e+00,
        -1.04610909e+00, -5.18701733e-03,  1.47790748e+00,
        -9.20864033e-01,  9.53905134e-01,  1.33342142e+00,
         1.17848036e+00],
       [-1.03019501e+00,  7.22504380e-01, -9.71890936e-01,
         6.93132066e-01,  1.17975754e+00, -3.83300706e-01,
        -1.04610909e+00, -1.39678967e-01,  1.47790748e+00,
        -9.20864033e-01, -6.94988026e-01,  2.34498250e+00,
         1.17848036e+00],
       [-1.46566609e+00,  7.22504380e-01,  8.09909113e-03,
         2.76317824e-01, -8.32151805e-01, -3.83300706e-01,
         8.43132697e-01, -8.12138713e-01, -6.76632341e-01,
        -9.20864033e-01, -6.94988026e-01, -6.89700735e-01,
        -2.19657581e+00],
       [ 6.02821534e-01, -1.38407465e+00,  9.88089118e-01,
        -1.68866360e+00,  1.35058003e+00, -3.83300706e-01,
         8.43132697e-01,  4.43119480e-01, -6.76632341e-01,
        -9.20864033e-01,  9.53905134e-01,  3.21860343e-01,
        -5.09047728e-01],
       [ 3.85085995e-01,  7.22504380e-01, -9.71890936e-01,
        -3.19131093e-01,  1.00893504e+00, -3.83300706e-01,
        -1.04610909e+00,  9.36256628e-01, -6.76632341e-01,
        -9.20864033e-01,  9.53905134e-01,  1.33342142e+00,
         1.17848036e+00],
       [ 8.20557073e-01, -1.38407465e+00, -9.71890936e-01,
         1.76494012e+00, -1.57238260e+00, -3.83300706e-01,
        -1.04610909e+00, -2.29340266e-01, -6.76632341e-01,
         4.71398260e+00, -2.34388119e+00,  2.34498250e+00,
         1.17848036e+00],
       [ 1.58263146e+00,  7.22504380e-01,  9.88089118e-01,
         5.74042282e-01,  1.35842312e-01, -3.83300706e-01,
        -1.04610909e+00, -1.84509616e-01, -6.76632341e-01,
         8.96828430e-01, -6.94988026e-01,  2.34498250e+00,
         1.17848036e+00],
       [-4.85856162e-01,  7.22504380e-01,  9.88089118e-01,
        -8.09515263e-02, -9.65013743e-01, -3.83300706e-01,
         8.43132697e-01,  5.77611430e-01, -6.76632341e-01,
        -9.20864033e-01,  9.53905134e-01, -6.89700735e-01,
        -5.09047728e-01],
       [ 1.47376369e+00,  7.22504380e-01, -9.71890936e-01,
         8.12221849e-01, -1.02195457e+00,  2.60891771e+00,
         8.43132697e-01, -4.08662865e-01, -6.76632341e-01,
         2.16921315e+00, -6.94988026e-01,  1.33342142e+00,
         1.17848036e+00],
       [ 6.02821534e-01,  7.22504380e-01, -9.71890936e-01,
         8.71766741e-01,  6.67290062e-01, -3.83300706e-01,
        -1.04610909e+00, -3.63832216e-01,  1.47790748e+00,
         1.62390542e+00, -6.94988026e-01,  1.33342142e+00,
         1.17848036e+00],
       [-4.85856162e-01,  7.22504380e-01, -9.71890936e-01,
         1.16949120e+00, -7.29407332e-02, -3.83300706e-01,
        -1.04610909e+00, -9.91461312e-01, -6.76632341e-01,
         1.44213617e+00, -6.94988026e-01, -6.89700735e-01,
         1.17848036e+00]])

In [658]:

preprocessor.get_feature_names_out()

array(['num_pipeline__age', 'num_pipeline__sex', 'num_pipeline__cp',
       'num_pipeline__trestbps', 'num_pipeline__chol',
       'num_pipeline__fbs', 'num_pipeline__restecg',
       'num_pipeline__thalach', 'num_pipeline__exang',
       'num_pipeline__oldpeak', 'num_pipeline__slope', 'num_pipeline__ca',
       'num_pipeline__thal'], dtype=object)

In [659]:
x_train=pd.DataFrame(preprocessor.fit_transform(x_train),columns=preprocessor.get_feature_names_out())
x_test=pd.DataFrame(preprocessor.fit_transform(x_test),columns=preprocessor.get_feature_names_out())

In [660]:
x_train

,num_pipeline__age,num_pipeline__sex,num_pipeline__cp,num_pipeline__trestbps,num_pipeline__chol,num_pipeline__fbs,num_pipeline__restecg,num_pipeline__thalach,num_pipeline__exang,num_pipeline__oldpeak,num_pipeline__slope,num_pipeline__ca,num_pipeline__thal
0,-1.356798,0.722504,0.008099,-0.616856,0.914034,-0.383301,0.843133,0.532781,-0.676632,-0.920864,0.953905,-0.689701,-0.509048
1,0.385086,0.722504,-0.971891,1.169491,0.439527,-0.383301,-1.046109,-1.753582,1.477907,-0.193787,0.953905,-0.689701,1.178480
2,-0.921327,0.722504,0.988089,1.169491,-0.300704,-0.383301,0.843133,-0.139679,-0.676632,2.350982,-0.694988,-0.689701,-0.509048
3,0.058483,-1.384075,0.008099,0.276318,0.059921,-0.383301,-1.046109,0.487950,-0.676632,0.351521,-0.694988,-0.689701,-0.509048
4,0.602822,0.722504,-0.971891,-0.795490,-0.319684,2.608918,0.843133,0.443119,1.477907,0.351521,0.953905,1.333421,1.178480
...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,-0.485856,0.722504,0.988089,0.574042,-0.262744,-0.383301,0.843133,0.577611,-0.676632,-0.375556,-0.694988,0.321860,1.178480
238,-0.376988,0.722504,0.988089,-2.165023,-0.376625,-0.383301,0.843133,0.174136,1.477907,-0.920864,0.953905,0.321860,1.178480
239,1.582631,0.722504,1.968079,1.764940,-0.243763,2.608918,-1.046109,-0.856969,-0.676632,-0.829979,-0.694988,0.321860,-0.509048
240,-0.921327,0.722504,-0.971891,-0.616856,0.040941,-0.383301,-1.046109,-0.274171,-0.676632,-0.193787,0.953905,-0.689701,1.178480
241,0.929425,-1.384075,0.008099,0.574042,-0.983994,-0.383301,0.843133,1.294902,-0.676632,-0.920864,0.953905,1.333421,-0.509048

In [661]:
x_test

,num_pipeline__age,num_pipeline__sex,num_pipeline__cp,num_pipeline__trestbps,num_pipeline__chol,num_pipeline__fbs,num_pipeline__restecg,num_pipeline__thalach,num_pipeline__exang,num_pipeline__oldpeak,num_pipeline__slope,num_pipeline__ca,num_pipeline__thal
0,0.351938,0.520416,-0.817224,0.692351,0.670699,-0.545777,-0.861892,-1.438221,1.285369,-0.399336,-0.485744,0.073151,-2.005978
1,0.585288,0.520416,2.004512,1.728753,0.921953,-0.545777,-0.861892,0.450638,-0.777987,-0.692823,-0.485744,-0.819288,0.942568
2,0.351938,0.520416,1.063933,0.692351,-2.469984,1.832251,1.160239,1.013277,-0.777987,-0.692823,1.073751,0.073151,0.942568
3,0.235263,-1.921538,-0.817224,-0.136771,3.455437,-0.545777,-0.861892,0.088942,1.285369,0.554499,-0.485744,0.965589,0.942568
4,1.985390,-1.921538,1.063933,-1.380454,0.440382,1.832251,-0.861892,-0.714828,-0.777987,-0.839567,1.073751,0.073151,-0.531705
...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,1.752039,0.520416,1.063933,0.174150,0.210065,-0.545777,-0.861892,-0.071812,-0.777987,0.627871,-0.485744,1.858028,0.942568
57,-0.464788,0.520416,1.063933,-0.395872,-1.004332,-0.545777,1.160239,0.611392,-0.777987,-0.839567,1.073751,-0.819288,-0.531705
58,1.635364,0.520416,-0.817224,0.381430,-1.067146,1.832251,1.160239,-0.272755,-0.777987,1.655078,-0.485744,0.965589,0.942568
59,0.701963,0.520416,-0.817224,0.433250,0.796326,-0.545777,-0.861892,-0.232566,1.285369,1.214846,-0.485744,0.965589,0.942568
60,-0.464788,0.520416,-0.817224,0.692351,-0.020251,-0.545777,-0.861892,-0.795205,-0.777987,1.068103,-0.485744,-0.819288,0.942568

In [662]:
from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
from xgboost import XGBRegressor
from sklearn.ensemble import RandomForestRegressor

In [663]:

## Train multiple models

models={
    'LinearRegression':LinearRegression(),
    'Lasso':Lasso(),
    'Ridge':Ridge(),
    'Elasticnet':ElasticNet(),
    'RandomForest':RandomForestRegressor(),
    'Xgboost':XGBRegressor()
}

In [664]:

trained_model_list=[]
model_list=[]
r2_list=[]

In [665]:

list(models)

['LinearRegression', 'Lasso', 'Ridge', 'Elasticnet', 'RandomForest', 'Xgboost']

In [666]:
for i in range(len(list(models))):
    model=list(models.values())[i]
    print(model)

LinearRegression()
Lasso()
Ridge()
ElasticNet()
RandomForestRegressor()
XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [667]:

models.keys()

dict_keys(['LinearRegression', 'Lasso', 'Ridge', 'Elasticnet', 'RandomForest', 'Xgboost'])

In [668]:
models.values()

dict_values([LinearRegression(), Lasso(), Ridge(), ElasticNet(), RandomForestRegressor(), XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)])

In [669]:

def evaluate_model(true,pred):
    r2=r2_score(true,pred)
    mae=mean_absolute_error(true,pred)
    mse=mean_squared_error(true,pred)

    return mae, mse,r2

In [670]:
for i in range(len(list(models))):
    model=list(models.values())[i]
    
    model.fit(x_train,y_train)

    #make_prediction
    y_pred=model.predict(x_test)

    #this is for the validaiton
    MAE,MSE,R2=evaluate_model(y_test,y_pred)


    print("model training performance",model)
    print("MSE:", MSE)
    print("MAE:",MAE)
    print("R2 SCORE:",R2)

    r2_list.append(R2)

    print("="*40)
    print("\n")

model training performance LinearRegression()
MSE: 0.10614185640852299
MAE: 0.24503753420968327
R2 SCORE: 0.5744031813619461
========================================


model training performance Lasso()
MSE: 0.25002015449540427
MAE: 0.4975613060560899
R2 SCORE: -0.002505382410990631
========================================


model training performance Ridge()
MSE: 0.10616248449883538
MAE: 0.2451949273877132
R2 SCORE: 0.5743204689437862
========================================


model training performance ElasticNet()
MSE: 0.25002015449540427
MAE: 0.4975613060560899
R2 SCORE: -0.002505382410990631
========================================


model training performance RandomForestRegressor()
MSE: 0.11626229508196723
MAE: 0.24163934426229508
R2 SCORE: 0.5338232758620689
========================================


model training performance XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)
MSE: 0.2607204981793253
MAE: 0.34561597568089847
R2 SCORE: -0.04541053203154011
========================================

In [671]:
trained_model_list

[]

In [672]:

model_list

[]

In [673]:
r2_list

[0.5744031813619461,
 -0.002505382410990631,
 0.5743204689437862,
 -0.002505382410990631,
 0.5338232758620689,
 -0.04541053203154011]

In [674]:

max(r2_list)

0.5744031813619461

In [675]:
# changing the model peramter

In [676]:
from sklearn.svm import SVR

In [677]:
model1=SVR(kernel='rbf')

In [678]:
model1.fit(x_train,y_train)

SVR()

In [679]:
y_pred1=model1.predict(x_test)

In [680]:
from sklearn.metrics import accuracy_score

In [681]:
accuracy_score=r2_score(y_pred1,y_test)
mean_squared_error=mean_squared_error(y_pred1,y_test)

In [682]:
accuracy_score

0.3396748389242681

In [683]:
mean_squared_error

0.1074509562535029